##########################################################################
#     Configure a Scheduled Cron Job to Backup a Router Periodically     #
##########################################################################
---
- name: Configure Cron Job to Backup Cisco Router
  hosts: iosxerouter
  gather_facts: false

  vars:
    tftp_server: 192.168.1.2

  tasks:
    - name: Get device hostname
      ios_facts:
        gather_subset:
        - hardware

    - name: Configure kron policy
      ios_config:
        lines:
        - cli copy system:/running-config tftp://{{ tftp_server }}/{{ ansible_net_hostname }}.cfg
        parents: kron policy-list backup-config
        before: no kron policy-list backup-config

    - name: Configure kron schedule
      ios_config:
        lines:
        - policy-list backup-config
        parents: kron occurrence weekly at 11:59 Fri recurring
        before: no kron occurrence weekly in 11:59 recurring
        replace: block

    - name: Save running-configuration
      ios_config:
        save_when: modified
