##########################################################################
#     Configure a Scheduled Cron Job to Backup a Router Periodically     #
##########################################################################
---
- name: Configure Cron Job to Backup Cisco Router
  hosts: iosxerouter
  gather_facts: false

  vars:
    tftp_server: 192.168.1.2

  tasks:
    - name: Retrieve device hostname
      ios_facts:
        gather_subset:
          - '!all'
          - '!min'
        gather_network_resources:
          - hostname

    - name: Store hostname in a variable
      set_fact:
        hostname: "{{ ansible_network_resources.hostname.hostname }}"

    - name: Configure kron policy
      ios_config:
        lines:
          - cli copy system:/running-config tftp://{{ tftp_server }}/{{ hostname }}.cfg
        parents: kron policy-list save-config
        before: no kron policy-list save-config
        match: exact

    - name: Configure kron schedule
      ios_config:
        lines:
          - policy-list save-config
        parents: kron occurrence weekly at 11:59 Fri recurring
        before: no kron occurrence weekly in 11:59 recurring
        match: exact

    - name: Save running-configuration
      ios_config:
        save_when: modified
