---
- name: Backup Cisco IOS Router or Switch
  hosts: iosxerouter
  gather_facts: false

  tasks:
    - name: Retrieve device hostname
      ios_facts:
        gather_subset:
          - '!all'
          - '!min'
        gather_network_resources:
          - hostname

    - name: Store hostname in a variable
      set_fact:
        hostname: "{{ ansible_network_resources.hostname.hostname }}"

    - name: Get current date
      local_action: command date +%Y-%b-%d
      register: date

    - name: Get current time
      local_action: command date +%H:%M
      register: time

    - name: Backup running-config to a file
      ios_config:
       backup: yes
       backup_options:
         filename: "{{ hostname }}_{{ time.stdout }}.cfg"
         dir_path: /home/backup/{{ date.stdout }}
