###################################################################################
#      Ensure That 'Switchport Nonegotiate' Is Configured On All Trunk Ports      #
###################################################################################
---
- name: Configure Switchport Nonegotiate on Trunk Ports
  hosts: ios
  gather_facts: no
  
  vars:
    intf_config_dict: {}
    trunk_intf_list: []

  tasks:
    - name: Retrieving all interfaces
      ios_command:
        commands: show running-config | include ^interface.*(thernet|channel).*$
      register: intf_list

    - name: Retrieving interfaces configurations
      ios_command:
        commands: show running-config {{ item }}
      register: intf_config
      loop: "{{ intf_list.stdout_lines[0] }}"

    - name: Placing interface configurations in a dictionary
      set_fact:
        intf_config_dict: "{{ intf_config_dict | default({}) | combine( { item.item : item.stdout[0] } ) }}"
      loop: "{{ intf_config.results }}"

    - name: Picking out trunk interfaces (excluding port-channel member ports)
      set_fact:
        trunk_intf_list: "{{ trunk_intf_list | default([]) + [item.key] }}"
      with_dict: "{{ intf_config_dict }}"
      when: ('\n switchport mode trunk' in item.value) and ('\n channel-group' not in item.value)

    - name: Configuring switchport nonegotiate on trunk interfaces
      ios_config:
        lines:
        - switchport nonegotiate
        parents: "{{ item }}"
      loop: "{{ trunk_intf_list }}"
