# ##################################################################################
#                       Configure Native Vlan On Trunk Ports                       #
# ##################################################################################
---
- name: Configure Native Vlan
  hosts: iosswitch
  gather_facts: false

  vars:
    native_vlan: 666
    trunk_intf_list: []

  tasks:
    - name: Configure vlan {{ native_vlan }}
      cisco.ios.ios_vlans:
        config:
          - name: "NATIVE-VLAN"
            vlan_id: "{{ native_vlan | int }}"
            state: active
            shutdown: disabled

    - name: Retrieve interfaces
      ios_command:
        commands: show running-config | include ^interface.*(thernet|channel).*$
      register: intf_list

    - name: Retrieve interface configurations
      ios_command:
        commands: show running-config {{ item }}
      register: intf_config
      loop: "{{ intf_list.stdout_lines[0] }}"
      no_log: true
      
    - name: Retrieve trunk interfaces
      set_fact:
        trunk_intf_list: "{{ trunk_intf_list | default([]) + [ item.item ] }}"
      loop: "{{ intf_config.results }}"
      when: ('\n switchport mode trunk' in item.stdout[0]) and ('\n channel-group' not in item.stdout[0])
      no_log: true
      
    - name: Configure native vlan on trunk interfaces
      ios_config:
        lines:
          - switchport trunk native vlan {{ native_vlan }}
        parents: "{{ item }}"
      loop: "{{ trunk_intf_list }}"
