---
- name: Configure Native Vlan
  hosts: iosswitch
  gather_facts: false

  vars:
    native_vlan: 666
    trunk_intf_list: []

  tasks:
    - name: Configure vlan {{ native_vlan }}
      ios_config:
        lines:
          - vlan {{ native_vlan }}

    - name: Configure vlan name
      ios_config:
        lines:
        - name NATIVE-VLAN
        parents: vlan {{ native_vlan }}

    - name: Retrieving all interfaces
      ios_command:
        commands: show running-config | include ^interface.*(thernet|channel).*$
      register: intf_list

    - name: Retrieving interfaces configurations
      ios_command:
        commands: show running-config {{ item }}
      register: intf_config
      loop: "{{ intf_list.stdout_lines[0] }}"

    - name: Retrieving trunk interfaces (excluding port-channel member ports)
      set_fact:
        trunk_intf_list: "{{ trunk_intf_list | default([]) + [ item.item ] }}"
      loop: "{{ intf_config.results }}"
      no_log: true
      when: ('\n switchport mode trunk' in item.stdout[0]) and ('\n channel-group' not in item.stdout[0])

    - name: Configure native vlan on trunk interfaces
      ios_config:
        lines:
          - switchport trunk native vlan {{ native_vlan }}
        parents: "{{ item }}"
      loop: "{{ trunk_intf_list }}"
