###################################################################################
#          Display All Physical Interfaces Without IP Address Configured          #
###################################################################################
---
- name: Display Physical Interfaces Without IP Addresses
  hosts: iosxe
  connection: ansible.netcommon.network_cli
  gather_facts: false

  tasks:
    - name: Get running configuration
      ios_command:
        commands:
        - show running-config
      register: rconfig

    - name: Get interfaces with no ip address
      set_fact:
        intf_config: "{{ rconfig.stdout[0] | regex_findall('(?m)^interface\\s.*thernet.*\\n(?:^.*\\n)\\s+no ip address$') }}"

    - name: Convert interface configuration list to string
      set_fact:
        intf_config_string: "{{ intf_config | join('\n') }}"

    - name: Get interfaces with no ip address
      set_fact:
        intf_list: "{{ intf_config_string | regex_findall('(?m)^interface.*$') }}"

    - name: Display interfaces with no ip address
      debug:
        var: intf_list
